[phases.setup]
nixPkgs = ["python311"]

[phases.install]
cmds = ["python -m pip install --user -r requirements.txt"]
 
[start]
cmd = "python -m uvicorn server_ormbg_only:app --host 0.0.0.0 --port $PORT" 